---
title: "Half-normal plots"
author: "Alicja Gosiewska"
date: "2 stycznia 2018"
output: html_document
---


```{r setup, echo = FALSE}
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r}
library(auditor)
```


# Half-normal plot

```{r}
data("corn", package = "hnp")
head(corn)
```


```{r}
model <- glm(cbind(y, m - y) ~ extract, family = binomial, data = corn)

set.seed(1234)
plotHalfNormal(model, score = TRUE)
```

```{r}
fit2_b <- glm(cbind(y, m - y) ~ extract, family = quasibinomial, data = corn)
plotHalfNormal(fit2_b, main = "Quasi-binomial model",  ylab = "Deviance residuals")

library("aods3")
fit3_b <- aodml(cbind(y, m - y) ~ extract, family = "bb", data = corn)
plotHalfNormal(fit3_b, ylab = "Deviance residuals", main = "Beta-binomial model")
library("lme4")
x <- factor(seq_len(nrow(corn)))
fit4_b <- glmer(cbind(y, m - y) ~ extract + (1 | x), family = binomial, data = corn)
plotHalfNormal(fit4_b, ylab = "Deviance residuals", main = "Binomial-logit-normal model")

```



# On quantile scale
```{r}
library(ggpubr)
p1 <- plotHalfNormal(model, main = "Binomial model",  ylab = "Deviance residuals quantiles", quant.scale = TRUE)
p2 <- plotHalfNormal(fit2_b, main = "Quasi-binomial model",  ylab = "Deviance residuals quantiles", quant.scale = TRUE)
p3 <- plotHalfNormal(fit3_b, ylab = "Deviance residuals quantiles", main = "Beta-binomial model", quant.scale = TRUE)
p4 <- plotHalfNormal(fit4_b, ylab = "Deviance residuals quantiles", main = "Binomial-logit-normal model", quant.scale = TRUE)
ggarrange(p1,p2,p3,p4, ncol=2)


```
